# Generated by Django 6.0.3 on 2026-03-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_travel_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="map_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
